displayName: ICal middleware
type: middleware

import: github.com/psumaps/icalmiddleware

summary: '[Auth] Authorize though ical endpoint'

testData:
  HeaderName: Authorization
  AllowSubnet:  "0.0.0.0/24"

